<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad5020a0d736572766963652e70726f746f12076d65737361676522390a" .
            "16476574496e74657273656374696f6e5265717565737412100a08736f6e" .
            "675f696473180120032804120d0a056c696d697418022001280522540a17" .
            "476574496e74657273656374696f6e526573706f6e7365120c0a0473697a" .
            "65180120012805122b0a0c696e74657273656374696f6e18022003280b32" .
            "152e6d6573736167652e55736572536f6e67496e666f223a0a0c55736572" .
            "536f6e67496e666f120f0a07757365725f696418012001280412190a1169" .
            "6e74657273656374696f6e5f73697a6518022001280532660a0c4e657465" .
            "6173654d7573696312560a0f476574496e74657273656374696f6e121f2e" .
            "6d6573736167652e476574496e74657273656374696f6e52657175657374" .
            "1a202e6d6573736167652e476574496e74657273656374696f6e52657370" .
            "6f6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

