<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>message.GetIntersectionResponse</code>
 */
class GetIntersectionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * 仅返回top数量
     *
     * Generated from protobuf field <code>int32 size = 1;</code>
     */
    private $size = 0;
    /**
     * Generated from protobuf field <code>repeated .message.UserSongInfo intersection = 2;</code>
     */
    private $intersection;

    public function __construct() {
        \GPBMetadata\Service::initOnce();
        parent::__construct();
    }

    /**
     * 仅返回top数量
     *
     * Generated from protobuf field <code>int32 size = 1;</code>
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * 仅返回top数量
     *
     * Generated from protobuf field <code>int32 size = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .message.UserSongInfo intersection = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIntersection()
    {
        return $this->intersection;
    }

    /**
     * Generated from protobuf field <code>repeated .message.UserSongInfo intersection = 2;</code>
     * @param \Message\UserSongInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIntersection($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Message\UserSongInfo::class);
        $this->intersection = $arr;

        return $this;
    }

}

