<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>message.UserSongInfo</code>
 */
class UserSongInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * 用户ID
     *
     * Generated from protobuf field <code>uint64 user_id = 1;</code>
     */
    private $user_id = 0;
    /**
     * 交集数量
     *
     * Generated from protobuf field <code>int32 intersection_size = 2;</code>
     */
    private $intersection_size = 0;

    public function __construct() {
        \GPBMetadata\Service::initOnce();
        parent::__construct();
    }

    /**
     * 用户ID
     *
     * Generated from protobuf field <code>uint64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * 用户ID
     *
     * Generated from protobuf field <code>uint64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * 交集数量
     *
     * Generated from protobuf field <code>int32 intersection_size = 2;</code>
     * @return int
     */
    public function getIntersectionSize()
    {
        return $this->intersection_size;
    }

    /**
     * 交集数量
     *
     * Generated from protobuf field <code>int32 intersection_size = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIntersectionSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->intersection_size = $var;

        return $this;
    }

}

